import type { GemType } from "@/types/gemstone";

export interface Category {
  type: GemType;
  image: string;
}

/** Faceted illustrations generated by scripts/generate-gems.mjs, one per gem type. */
const illustrations: Record<string, string> = {
  Ruby: "/images/gems/ruby.svg",
  Sapphire: "/images/gems/sapphire.svg",
  Spinel: "/images/gems/spinel.svg",
  Alexandrite: "/images/gems/alexandrite.svg",
  "Cat's Eye": "/images/gems/cats-eye.svg",
  Emerald: "/images/gems/emerald.svg",
};

export const categories: Category[] = (
  ["Ruby", "Sapphire", "Spinel", "Alexandrite", "Cat's Eye", "Emerald"] as GemType[]
).map((type) => ({ type, image: illustrations[type] }));
